### PR TITLE
Reset to upstream master + small change for CentOS

### PR DESCRIPTION
**Pull request by vitroth**
Our chef-runit cookbook was very out of date vs the upstream master.

Upon review, the two small patches in our fork were no longer required, mainly due to those sections of the upstream cookbook being completely rewritten in the meantime.  The bugfixes done in our fork were incorporated into the rewrite.

Testing the upstream cookbook on CentOS revealed that the chef service resource was not automatically detecting systemd presence (probably because we use an old chef version), so this also adds a small patch to force the service provider type to Systemd on CentOS/RedHat 7.

The relevant parts for review are the two commits from our fork which I reverted and the CentOS fix.  Preliminary testing indicates that everything is working as expected, but I'll be running a full suite of system tests.

Reviewers: @shr3kst3r and @krobertson (as author of our original changes which I've determined are no longer required)

### CODE REVIEW

**Comment by vitroth** [comment]
Part of #SRE-915

**Comment by vitroth** [comment]
System tests passing:
http://tc.apcera.net/viewType.html?buildTypeId=SystemTestsApceraSetup_ApceraSetupDeployTestBranchesVSphereThreaded&branch_SystemTests=SRE-915-runit-upstream-reset&tab=buildTypeStatusDiv
http://tc.apcera.net/project.html?projectId=SystemTests&branch_SystemTests=SRE-915-runit-upstream-reset

**Comment by shr3kst3r** [comment]
It kind of looks like this undoes these commits:
https://github.com/apcera/chef-runit/commit/b0fd2fe7e4ddca0fe7c2ca0634c032f6012d4fb3
https://github.com/apcera/chef-runit/commit/816c1ecab2f413b848fd4ff7348ce868496341cc

I did a casual glance, and I might be wrong.  I also do not expect that the unit tests would catch a log file being in the wrong place, which seems to be what was fixed.

**Comment by vitroth** [comment]
Yes, those commits were removed as they were the old changes we had made, and I determined the complete rewrite of those sections in the upstream had independently fixed the bugs that Ken fixed in our fork.

**Comment by shr3kst3r** [comment]
Ah, sorry.  I missed "as author of our original changes which I've determined are no longer required".

LGTM

**Comment by krobertson** [comment]
Think it is difficult to actually review much with so much changed upstream. Additionally, the changes we had applied were over 2 years ago and unfortunately don't reference a jira ticket, so context on why it was required or what it was fixing is weak.

I think if everything still works and can confirm logging on everything is still present, LGTM. Maybe just grab log output of an existing master run, and one on this branch, and ensure the same processes are all there.

**Comment by vitroth** [comment]
Good idea, comparing logs on a TC run... 

I've looked through the logs in the Artifacts on this run and all the logs appear to be there as expected.
http://tc.apcera.net/viewLog.html?buildId=258592&buildTypeId=SystemTestsApceraSetup_ApceraSetupDeployTestBranchesVSphereThreaded&tab=artifacts

**Comment by vitroth** [comment]
@juanman2 please review for merge

**Comment by juanman2** [comment]
OK to merge

**Pull request merged**
